import assert from 'node:assert/strict';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import {chromium} from 'playwright';
const prefix='.',software=process.env.POMME_SOFTWARE_GPU==='1',errors=[];
const water=await readFile(new URL('../src/shaders/water.wgsl',import.meta.url),'utf8');
const candidate=await readFile(new URL('../src/shaders/common.wgsl',import.meta.url),'utf8');
const fixed=await readFile(new URL('./fixtures/fixed-shadow.wgsl',import.meta.url),'utf8');
const shadowStart=candidate.indexOf('const SUN_SHADOW_SEARCH');
assert.ok(shadowStart>0,'Production source must contain the bounded variable-penumbra filter');
const common={baseline:candidate.slice(0,shadowStart)+fixed,candidate};
const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH??'/usr/bin/chromium',headless:true,args:['--no-sandbox','--enable-unsafe-webgpu',...(software?['--use-angle=swiftshader','--enable-features=Vulkan','--use-vulkan=swiftshader']:[])]});
try{
 const syntheticPage=await browser.newPage();syntheticPage.on('pageerror',error=>errors.push(error.message));await syntheticPage.goto(new URL('/src/shaders/common.wgsl',process.env.POMME_URL??'http://127.0.0.1:5173').href);
 const synthetic=await syntheticPage.evaluate(async(common)=>{
  const check=(ok,message)=>{if(!ok)throw new Error(message);},adapter=await navigator.gpu.requestAdapter();check(adapter,'WebGPU adapter is required');const device=await adapter.requestDevice();
  const validation=[];device.addEventListener('uncapturederror',event=>validation.push(event.error.message));const size=256,resources=[];const texture=options=>{const result=device.createTexture(options);resources.push(result);return result;};
  const shadow=texture({size:[size,size],format:'depth32float',usage:GPUTextureUsage.RENDER_ATTACHMENT|GPUTextureUsage.TEXTURE_BINDING}),target=texture({size:[size,size],format:'rgba8unorm',usage:GPUTextureUsage.RENDER_ATTACHMENT|GPUTextureUsage.COPY_SRC});
  const uniform=device.createBuffer({size:448,usage:GPUBufferUsage.UNIFORM|GPUBufferUsage.COPY_DST}),readback=device.createBuffer({size:size*size*4,usage:GPUBufferUsage.COPY_DST|GPUBufferUsage.MAP_READ});resources.push(uniform,readback);
  const fullScreen=`@vertex fn vs(@builtin(vertex_index) i:u32)->@builtin(position) vec4<f32>{var p=array<vec2<f32>,3>(vec2<f32>(-1.0,-1.0),vec2<f32>(3.0,-1.0),vec2<f32>(-1.0,3.0));return vec4<f32>(p[i],0.0,1.0);}`;
  const depthCode=fullScreen+`@group(0) @binding(0) var<uniform> source_frame:array<vec4<f32>,28>;@fragment fn fs(@builtin(position) p:vec4<f32>)->@builtin(frag_depth) f32{let uv=p.xy/256.0;let depth=0.2+source_frame[22].y*(uv.x-0.5);return select(1.0,depth,(uv.x>=0.25&&uv.x<0.75)||source_frame[22].z>0.5);}`;
  const depthModule=device.createShaderModule({code:depthCode}),depthPipeline=await device.createRenderPipelineAsync({layout:'auto',vertex:{module:depthModule,entryPoint:'vs'},fragment:{module:depthModule,entryPoint:'fs',targets:[]},depthStencil:{format:'depth32float',depthWriteEnabled:true,depthCompare:'always'}});
  const depthGroup=device.createBindGroup({layout:depthPipeline.getBindGroupLayout(0),entries:[{binding:0,resource:{buffer:uniform}}]});
  const fragment=`@fragment fn fs(@builtin(position) p:vec4<f32>)->@location(0) vec4<f32>{let uv=p.xy/256.0;let normal=normalize(vec3<f32>(-20.0*frame.world_time.y,0.0,1.0));let depth=frame.world_time.x+frame.world_time.y*(uv.x-0.5)+(1.0-normal.z)*0.0012;let world=vec3<f32>((uv.x*2.0-1.0)*8.0,(1.0-uv.y*2.0)*8.0,depth*320.0);let v=terrain_shadow(world,normal);return vec4<f32>(v,v,v,1.0);}`;
  const pipelines={};for(const[name,code]of Object.entries(common)){const module=device.createShaderModule({label:name,code:code+fullScreen+fragment}),info=await module.getCompilationInfo();check(!info.messages.some(m=>m.type==='error'),`${name}: ${info.messages.map(m=>m.message).join('; ')}`);pipelines[name]=await device.createRenderPipelineAsync({layout:'auto',vertex:{module,entryPoint:'vs'},fragment:{module,entryPoint:'fs',targets:[{format:'rgba8unorm'}]}});}
  const sampler=device.createSampler({compare:'less-equal',magFilter:'linear',minFilter:'linear'}),groups={};for(const[name,pipeline]of Object.entries(pipelines))groups[name]=device.createBindGroup({layout:pipeline.getBindGroupLayout(0),entries:[{binding:0,resource:{buffer:uniform}},{binding:1,resource:shadow.createView()},{binding:2,resource:sampler}]});
  const data=new Float32Array(112);data[0]=data[5]=data[10]=data[15]=1;data[16]=data[21]=1/8;data[26]=1/320;data[31]=1;data[38]=1;data[55]=1;data[59]=1;data[60]=data[61]=size;
  const row=async(name,quality,receiver,slope=0,wholePlane=false)=>{data[62]=quality;data[88]=receiver;data[89]=slope;data[90]=Number(wholePlane);device.queue.writeBuffer(uniform,0,data);const encoder=device.createCommandEncoder();const depth=encoder.beginRenderPass({colorAttachments:[],depthStencilAttachment:{view:shadow.createView(),depthLoadOp:'clear',depthClearValue:1,depthStoreOp:'store'}});depth.setPipeline(depthPipeline);depth.setBindGroup(0,depthGroup);depth.draw(3);depth.end();const pass=encoder.beginRenderPass({colorAttachments:[{view:target.createView(),loadOp:'clear',storeOp:'store',clearValue:{r:0,g:0,b:0,a:1}}]});pass.setPipeline(pipelines[name]);pass.setBindGroup(0,groups[name]);pass.draw(3);pass.end();encoder.copyTextureToBuffer({texture:target},{buffer:readback,bytesPerRow:size*4},[size,size]);device.queue.submit([encoder.finish()]);await readback.mapAsync(GPUMapMode.READ);const values=new Uint8Array(readback.getMappedRange()),result=Array.from({length:size},(_,x)=>values[(128*size+x)*4]);readback.unmap();return result;};
  try{const result={};for(const name of['baseline','candidate']){result[name]={};for(const quality of[0,1,2]){const near=await row(name,quality,.205),far=await row(name,quality,.30),repeat=await row(name,quality,.30);check(far.every((value,index)=>value===repeat[index]),`${name} ${quality} fixed-input shadow samples must be deterministic`);const transitions=values=>values.slice(40,88).filter(value=>value>4&&value<251).length;check(near[16]===255&&far[16]===255&&near[128]===0&&far[128]===0,`${name} ${quality} must preserve full light/umbra`);result[name][quality]={near,far,nearTransition:transitions(near),farTransition:transitions(far),repeatExact:true};}}
   check(result.baseline[1].nearTransition===result.baseline[1].farTransition,'Baseline fixed kernel control must be distance independent');for(const quality of[1,2])check(result.candidate[quality].farTransition>=result.candidate[quality].nearTransition+2,`Candidate ${quality} far blocker must produce wider penumbra`);for(const distance of['near','far'])check(result.baseline[0][distance].every((value,index)=>value===result.candidate[0][distance][index]),'Low hardware comparison must remain pixel exact');const slopes=[];for(const quality of[1,2])for(const slope of[-.3,-.2,.2,.3]){const profile=await row('candidate',quality,.30,slope),plain=result.candidate[quality].far;const mismatch=profile.reduce((n,v,i)=>n+(v!==plain[i]?1:0),0),maxError=Math.max(...profile.map((v,i)=>Math.abs(v-plain[i])));check(maxError<=1,`Analytic receiver-plane shear must preserve known separation ${quality}/${slope}: ${maxError}`);const unblocked=await row('candidate',quality,.2,slope,true);check(unblocked.slice(4,-4).every(v=>v===255),`Sloped receiver ${quality}/${slope} must not self-shadow`);slopes.push({quality,slope,mismatch,maxByteError:maxError,unblockedReceiverExact:true});}check(validation.length===0,validation.join('; '));return{dimensions:size,result,slopes,errors:validation};
  }finally{for(const resource of resources)resource.destroy();device.destroy();}
 },common);await syntheticPage.close();
 const actual={};for(const name of['baseline','candidate']){
  const page=await browser.newPage({viewport:{width:260,height:260}});page.on('pageerror',error=>errors.push(error.message));await page.route('**/src/shaders/common.wgsl',route=>route.fulfill({status:200,contentType:'text/plain',body:common[name]}));
  await page.goto(new URL('/src/shaders/common.wgsl',process.env.POMME_URL??'http://127.0.0.1:5173').href);
  actual[name]=await page.evaluate(async()=>{
   const {createRenderer}=await import('/src/renderer.js');const check=(ok,message)=>{if(!ok)throw new Error(message);};document.body.replaceChildren();const canvas=document.createElement('canvas');canvas.style.cssText='width:256px;height:256px';document.body.append(canvas);const samples=[],renderer=await createRenderer(canvas,{onGpuSample:s=>samples.push(s)});
   const bounds={min:[-20,-1,-20],max:[20,10,20]},quad=(cx,y,cz,r,color)=>new Float32Array([[-r,-r],[-r,r],[r,r],[-r,-r],[r,r],[r,-r]].flatMap((p,i)=>[p[0]+cx,y,p[1]+cz,0,1,0,...color,1,i%2,i%3,0,1|512|(15<<10)]));
   const frame={eye:[0,22,0],yaw:0,pitch:-Math.PI/2,timeSeconds:10,dayPhase:.12,scale:1};const result={};
   try{renderer.setTextureAtlas({pixelsRGBA:new Uint8Array([255,255,255,255]),width:1,height:1,tiles:[{id:0,x:0,y:0,width:1,height:1}]});renderer.configureWorld({...bounds,fogDensity:0});renderer.uploadChunk('receiver',quad(0,0,0,20,[.03,.6,.03]),[],bounds,{stride:14});renderer.uploadChunk('near',quad(-5,1,-4,1.5,[.8,.01,.01]),[],{min:[-6.5,1,-5.5],max:[-3.5,1.001,-2.5]},{stride:14});renderer.uploadChunk('far',quad(5,8,-4,1.5,[.8,.01,.01]),[],{min:[3.5,8,-5.5],max:[6.5,8.001,-2.5]},{stride:14});renderer.uploadChunk('water',[],quad(0,.25,0,8,[.2,.4,.8]),{min:[-8,.25,-8],max:[8,.251,8]},{stride:14});
    for(const quality of['low','balanced','high']){const frames=[];for(let i=0;i<3;i++){renderer.render({...frame,quality});const hdr=await renderer.readPixels(),depth=await renderer.readPixels({source:'depth'});check(renderer.stats().lastError===null,renderer.stats().lastError);frames.push({hdr:Array.from(hdr.pixels),depth:Array.from(depth.pixels),width:hdr.width,height:hdr.height,stats:renderer.stats()});}
     check(frames[1].stats.shadowUpdates===frames[0].stats.shadowUpdates&&frames[2].stats.shadowUpdates===frames[0].stats.shadowUpdates,'Soft shadow filter must reuse stable cached static depth');check(frames[2].stats.meshUploadCount===frames[0].stats.meshUploadCount,'Soft shadow filter must not upload static geometry');const shadow=await renderer.readPixels({source:'shadow'});const hash=await crypto.subtle.digest('SHA-256',shadow.pixels);result[quality]={frames,shadowHash:Array.from(new Uint8Array(hash),v=>v.toString(16).padStart(2,'0')).join('')};}
    return{result,samples,adapter:renderer.stats().adapterInfo};
   }finally{renderer.destroy();canvas.remove();}
  });await page.close();
 }
 const compare=(a,b)=>a.reduce((sum,value,index)=>sum+(value!==b[index]?1:0),0),actualSummary={};for(const quality of['low','balanced','high']){const a=actual.baseline.result[quality],b=actual.candidate.result[quality];assert.equal(a.shadowHash,b.shadowHash,`${quality} cached shadow depth must be exact`);const frames=a.frames.map((frame,index)=>{const candidate=b.frames[index],depthMismatch=compare(frame.depth,candidate.depth),hdrMismatch=compare(frame.hdr,candidate.hdr);assert.equal(depthMismatch,0,`${quality} frame${index} camera depth must be exact`);if(quality==='low')assert.equal(hdrMismatch,0,'Low HDR must remain pixel exact');return{frame:index,depthMismatch,hdrMismatch,candidateStats:candidate.stats};});if(quality!=='low')assert.ok(frames[0].hdrMismatch>20,`${quality} improvement must change actual receiver pixels`);actualSummary[quality]={frames,shadowDepthMismatch:0};}
 assert.deepEqual(errors,[]);const proof={productionCandidate:true,fixedKernelControl:true,photonCodeReused:false,synthetic,actualRenderer:actualSummary,profileSamples:{baseline:actual.baseline.samples,candidate:actual.candidate.samples},adapter:actual.candidate.adapter};await mkdir(`${prefix}/test-results`,{recursive:true});await writeFile(`${prefix}/test-results/pcss.json`,JSON.stringify({softwareSmoke:software,proof,errors},null,2));console.log(JSON.stringify({softwareSmoke:software,transitions:Object.fromEntries(Object.entries(synthetic.result).map(([mode,qualities])=>[mode,Object.fromEntries(Object.entries(qualities).map(([quality,result])=>[quality,{near:result.nearTransition,far:result.farTransition}]))])),receiverPlaneControls:synthetic.slopes,actualRendererCases:Object.values(actualSummary).reduce((count,result)=>count+result.frames.length,0),errors},null,2));
}finally{await browser.close();}
