import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';
const software = process.env.POMME_SOFTWARE_GPU === '1';
const browser = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH ?? '/usr/bin/chromium', headless: true, args: ['--no-sandbox', '--enable-unsafe-webgpu', ...(software ? ['--use-angle=swiftshader', '--enable-features=Vulkan', '--use-vulkan=swiftshader'] : [])] });
const context = await browser.newContext({ viewport: { width: 1280, height: 720 } });
const page = await context.newPage();
const errors = [];
page.on('pageerror', error => errors.push(error.message));
page.on('console', message => { if (message.type() === 'error' && !message.text().includes('favicon.ico')) errors.push(message.text()); });
try {
  await page.goto(process.env.POMME_URL ?? 'http://127.0.0.1:5173');
  await page.waitForFunction(() => document.documentElement.dataset.engine === 'ready' || document.documentElement.dataset.engine === 'error', null, { timeout: 60000 });
  assert.equal(await page.locator('html').getAttribute('data-engine'), 'ready', await page.locator('#error').textContent());
  await page.evaluate(() => { document.querySelector('#cycle').checked = false; document.querySelector('#adaptive').checked = false; });
  await page.waitForTimeout(500);
  const first = await page.evaluate(() => window.pomme.renderer.stats());
  assert.equal(first.totalChunks, 64);
  assert.ok(first.triangles > 1000);
  console.log('World ready; checking cached shadows and block edits.');
  await page.waitForTimeout(500);
  const stable = await page.evaluate(() => window.pomme.renderer.stats());
  assert.equal(stable.shadowUpdates, first.shadowUpdates, 'stationary lighting must reuse the shadow map');
  const cacheProof = await page.evaluate(() => {
    const args = { eye: window.pomme.player.eye, yaw: 0, pitch: -0.12, timeSeconds: 10, dayPhase: 0.22, revision: window.pomme.revision, quality: 'balanced', scale: 0.85 };
    window.pomme.renderer.render(args);
    const a = window.pomme.renderer.stats();
    window.pomme.renderer.render({ ...args, yaw: 0.1 });
    const b = window.pomme.renderer.stats();
    return { shadowBefore: a.shadowUpdates, shadowAfter: b.shadowUpdates, skyBefore: a.skyCacheUpdates, skyAfter: b.skyCacheUpdates, uploadsBefore: a.meshUploadCount, uploadsAfter: b.meshUploadCount };
  });
  assert.equal(cacheProof.shadowBefore, cacheProof.shadowAfter, 'camera rotation reuses world-space shadows');
  assert.equal(cacheProof.skyBefore, cacheProof.skyAfter, 'camera rotation reuses the sky/cloud environment');
  assert.equal(cacheProof.uploadsBefore, cacheProof.uploadsAfter, 'drawing stable terrain does not upload geometry again');

  const before = await page.evaluate(() => window.pomme.core.block_get(65, 40, 65));
  const updates = stable.shadowUpdates;
  const revision = await page.evaluate(() => window.pomme.revision);
  await page.evaluate(() => window.pomme.edit(65, 40, 65, 8));
  await page.waitForFunction(r => window.pomme.revision > r, revision);
  await page.waitForFunction(n => window.pomme.renderer.stats().shadowUpdates > n, updates);
  assert.equal(await page.evaluate(() => window.pomme.core.block_get(65, 40, 65)), 8);
  await page.evaluate(id => window.pomme.edit(65, 40, 65, id), before);

  await page.locator('#play').click();
  await page.waitForFunction(() => document.pointerLockElement?.id === 'world' && document.querySelector('#welcome').hidden);
  // Begin above trees so input verification cannot be blocked by a terrain step.
  await page.evaluate(() => { window.pomme.player.position = [64.5, 48, 88.5]; window.pomme.player.verticalSpeed = 0; });
  const initialPosition = await page.evaluate(() => [...window.pomme.player.position]);
  await page.keyboard.down('w');
  await page.waitForTimeout(600);
  await page.keyboard.up('w');
  const moved = await page.evaluate(() => [...window.pomme.player.position]);
  assert.ok(Math.hypot(moved[0] - initialPosition[0], moved[2] - initialPosition[2]) > 0.05, 'WASD moves the player under pointer lock');
  await page.keyboard.press('KeyE');
  await page.waitForFunction(() => !document.pointerLockElement);

  await page.locator('#settings-toggle').click();
  await page.locator('#quality').selectOption('low');
  await page.locator('#resolution').evaluate(element => { element.value = '0.6'; element.dispatchEvent(new Event('input')); });
  await page.waitForTimeout(300);
  const low = await page.evaluate(() => window.pomme.renderer.stats());
  assert.ok(low.renderWidth < first.renderWidth, 'resolution slider changes real render targets');
  await page.locator('#sun').evaluate(element => { element.value = '0.75'; element.dispatchEvent(new Event('input')); });
  await page.waitForTimeout(300);
  await mkdir(new URL('../test-results/', import.meta.url), { recursive: true });
  await page.screenshot({ path: new URL('../test-results/night.png', import.meta.url).pathname });
  await page.locator('#sun').evaluate(element => { element.value = '0.22'; element.dispatchEvent(new Event('input')); });
  await page.locator('#quality').selectOption('balanced');
  await page.locator('#settings-toggle').click();
  await page.evaluate(() => { document.querySelector('#welcome').hidden = true; document.querySelector('#pause').hidden = true; });
  await page.waitForTimeout(300);
  await page.screenshot({ path: new URL('../test-results/day.png', import.meta.url).pathname });
  await page.evaluate(() => window.pomme.startBenchmark());
  console.log('Running fixed-camera 30-second benchmark.');
  assert.equal(await page.locator('#quality').isDisabled(), true);
  await page.waitForFunction(() => window.pomme.benchmark != null, null, { timeout: 45000 });
  const result = await page.evaluate(() => window.pomme.benchmark);
  assert.ok(result.frames.samples > 5);
  assert.ok(result.frames.p95Ms > 0);
  assert.equal(result.cancelled, false);
  await writeFile(new URL('../test-results/benchmark.json', import.meta.url), JSON.stringify(result, null, 2));
  assert.equal(await page.locator('#quality').isDisabled(), false);
  const savedWorld = await page.evaluate(() => localStorage.getItem('pomme-web-world-v1'));
  const fallback = await context.newPage();
  await fallback.addInitScript(() => Object.defineProperty(navigator, 'gpu', { value: undefined, configurable: true }));
  await fallback.goto(process.env.POMME_URL ?? 'http://127.0.0.1:5173');
  assert.equal(await fallback.locator('#error').isVisible(), true, 'unsupported WebGPU shows a useful error');
  await fallback.goto('about:blank');
  assert.equal(await page.evaluate(() => localStorage.getItem('pomme-web-world-v1')), savedWorld, 'failed startup must not erase saved edits');
  await fallback.close();
  assert.deepEqual(errors.filter(x => !x.includes('404 (Not Found)')), [], 'no JS or WebGPU validation errors');
  console.log(JSON.stringify({ validation: 'passed', softwareGPU: software, stats: low, benchmark: result }, null, 2));
} finally { await browser.close(); }
