[package]
name="pomme-upstream-generation-wasm"
version="0.1.0"
edition="2024"
license="GPL-3.0-or-later"
publish=false
[workspace]
resolver="2"
exclude=["target/source"]
[lib]
crate-type=["cdylib","rlib"]
[dependencies]
pumpkin-world={path="target/source/pumpkin-world"}
pumpkin-util={path="target/source/pumpkin-util"}
pumpkin-data={path="target/source/pumpkin-data"}
futures="0.3"
serde_json="1.0"
tokio={version="1.48",default-features=false,features=["io-util"]}
[target.'cfg(target_arch="wasm32")'.dependencies]
uuid={version="1.19",features=["js"]}
wasm-bindgen="=0.2.129"
getrandom={version="0.3",features=["wasm_js"]}
getrandom_02={package="getrandom",version="0.2",features=["js"]}
[profile.release]
opt-level=2
lto=false
codegen-units=16
panic="abort"
strip=true
[build-dependencies]
serde_json="1.0"
