[package]
name = "pomme-shaderpack"
version = "0.1.0"
edition = "2024"
default-run = "pomme-shaderpack"
license = "GPL-3.0-or-later"

[features]
vulkan = ["dep:shaderc", "dep:pyronyx", "dep:pomme-gpu-allocator"]

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
glam = { workspace = true }
image = { version = "0.25", default-features = false, features = ["png"] }
khronos-egl = { version = "6", features = ["dynamic"] }
libloading = "0.9"
regex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
zip = { workspace = true }
glutin = "0.32"
glutin-winit = "0.5"
raw-window-handle = "0.6"
winit = "0.30"
shaderc = { version = "0.10", optional = true }
pyronyx = { workspace = true, optional = true }
pomme-gpu-allocator = { path = "../pomme-gpu-allocator", optional = true }

[build-dependencies]
gl_generator = "0.14"
